# Generated by Django 5.0.1 on 2026-01-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='cpf',
            field=models.CharField(db_index=True, max_length=11),
        ),
    ]
