# Generated by Django 5.0.1 on 2026-01-25 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_professional_approved_at_professional_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='address',
            field=models.TextField(default='Endereço não informado'),
        ),
        migrations.AddField(
            model_name='professional',
            name='area_of_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='professional',
            name='council_name',
            field=models.CharField(default='Outros', max_length=50),
        ),
        migrations.AddField(
            model_name='professional',
            name='council_number',
            field=models.CharField(default='00000', max_length=50),
        ),
        migrations.AddField(
            model_name='professional',
            name='education',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='professional',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professional',
            name='graduation_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='professional',
            name='institution',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='professional',
            name='specialty',
            field=models.CharField(default='Geral', max_length=255),
        ),
    ]
