# Generated by Django 5.0.1 on 2026-01-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0004_professional_address_professional_area_of_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='address',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='specialty',
        ),
        migrations.AddField(
            model_name='professional',
            name='city',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='professional',
            name='complement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='neighborhood',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='professional',
            name='number',
            field=models.CharField(default='S/N', max_length=20),
        ),
        migrations.AddField(
            model_name='professional',
            name='state',
            field=models.CharField(default='SP', max_length=2),
        ),
        migrations.AddField(
            model_name='professional',
            name='street',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='professional',
            name='zip_code',
            field=models.CharField(default='00000-000', max_length=9),
        ),
        migrations.AlterField(
            model_name='professional',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='professional',
            name='council_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='professional',
            name='council_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='professional',
            name='education',
            field=models.CharField(choices=[('Agente Comunitário de Saúde', 'Agente Comunitário de Saúde'), ('Agente de Combate às Endemias', 'Agente de Combate às Endemias'), ('Acompanhante Terapêutico', 'Acompanhante Terapêutico'), ('Administrador Hospitalar', 'Administrador Hospitalar'), ('Analista de Regulação em Saúde', 'Analista de Regulação em Saúde'), ('Antropólogo da Saúde', 'Antropólogo da Saúde'), ('Aromaterapeuta', 'Aromaterapeuta'), ('Arteterapeuta', 'Arteterapeuta'), ('Assistente Social (na saúde)', 'Assistente Social (na saúde)'), ('Audiologista', 'Audiologista'), ('Auxiliar de Enfermagem', 'Auxiliar de Enfermagem'), ('Auxiliar de Farmácia', 'Auxiliar de Farmácia'), ('Auxiliar de Saúde Bucal', 'Auxiliar de Saúde Bucal'), ('Bioquímico', 'Bioquímico'), ('Biomédico', 'Biomédico'), ('Biólogo (atuando na saúde)', 'Biólogo (atuando na saúde)'), ('Citotécnico', 'Citotécnico'), ('Cosmetólogo', 'Cosmetólogo'), ('Cuidador de Idosos', 'Cuidador de Idosos'), ('Dentista (Cirurgião-Dentista)', 'Dentista (Cirurgião-Dentista)'), ('Dosimetrista', 'Dosimetrista'), ('Doula', 'Doula'), ('Educador Físico (Bacharel)', 'Educador Físico (Bacharel)'), ('Educador em Saúde', 'Educador em Saúde'), ('Enfermeiro', 'Enfermeiro'), ('Engenheiro Biomédico', 'Engenheiro Biomédico'), ('Epidemiologista', 'Epidemiologista'), ('Esteticista', 'Esteticista'), ('Farmacêutico', 'Farmacêutico'), ('Farmacêutico Clínico', 'Farmacêutico Clínico'), ('Farmacêutico Hospitalar', 'Farmacêutico Hospitalar'), ('Farmacêutico Industrial', 'Farmacêutico Industrial'), ('Fisioterapeuta', 'Fisioterapeuta'), ('Fonoaudiólogo', 'Fonoaudiólogo'), ('Gerontólogo', 'Gerontólogo'), ('Gestor Hospitalar', 'Gestor Hospitalar'), ('Gestor em Saúde', 'Gestor em Saúde'), ('Histotécnico', 'Histotécnico'), ('Massoterapeuta', 'Massoterapeuta'), ('Musicoterapeuta', 'Musicoterapeuta'), ('Naturopata', 'Naturopata'), ('Nutricionista', 'Nutricionista'), ('Obstetriz', 'Obstetriz'), ('Optometrista', 'Optometrista'), ('Óptico', 'Óptico'), ('Operador de Raios-X', 'Operador de Raios-X'), ('Ortesista e Protesista', 'Ortesista e Protesista'), ('Osteopata', 'Osteopata'), ('Parteira Tradicional', 'Parteira Tradicional'), ('Patologista Clínico (não médico)', 'Patologista Clínico (não médico)'), ('Podólogo', 'Podólogo'), ('Protético Dentário', 'Protético Dentário'), ('Psicanalista', 'Psicanalista'), ('Psicólogo', 'Psicólogo'), ('Quiropraxista', 'Quiropraxista'), ('Radiologista Tecnólogo', 'Radiologista Tecnólogo'), ('Reflexoterapeuta', 'Reflexoterapeuta'), ('Sanitarista', 'Sanitarista'), ('Sociólogo da Saúde', 'Sociólogo da Saúde'), ('Técnico em Administração Hospitalar', 'Técnico em Administração Hospitalar'), ('Técnico em Análises Clínicas', 'Técnico em Análises Clínicas'), ('Técnico em Audiometria', 'Técnico em Audiometria'), ('Técnico em Banco de Sangue', 'Técnico em Banco de Sangue'), ('Técnico em Enfermagem', 'Técnico em Enfermagem'), ('Técnico em Equipamentos Biomédicos', 'Técnico em Equipamentos Biomédicos'), ('Técnico em Farmácia', 'Técnico em Farmácia'), ('Técnico em Gerontologia', 'Técnico em Gerontologia'), ('Técnico em Hemoterapia', 'Técnico em Hemoterapia'), ('Técnico em Histologia', 'Técnico em Histologia'), ('Técnico em Imobilizações Ortopédicas', 'Técnico em Imobilizações Ortopédicas'), ('Técnico em Imagenologia', 'Técnico em Imagenologia'), ('Técnico em Nutrição e Dietética', 'Técnico em Nutrição e Dietética'), ('Técnico em Óptica', 'Técnico em Óptica'), ('Técnico em Prótese Dentária', 'Técnico em Prótese Dentária'), ('Técnico em Radiologia', 'Técnico em Radiologia'), ('Técnico em Registros e Informações em Saúde', 'Técnico em Registros e Informações em Saúde'), ('Técnico em Saúde Bucal', 'Técnico em Saúde Bucal'), ('Técnico em Saúde Pública', 'Técnico em Saúde Pública'), ('Técnico em Vigilância em Saúde', 'Técnico em Vigilância em Saúde'), ('Tecnólogo em Análises Clínicas', 'Tecnólogo em Análises Clínicas'), ('Tecnólogo em Estética e Cosmética', 'Tecnólogo em Estética e Cosmética'), ('Tecnólogo em Oftálmica', 'Tecnólogo em Oftálmica'), ('Tecnólogo em Radiologia', 'Tecnólogo em Radiologia'), ('Tecnólogo em Saúde Pública', 'Tecnólogo em Saúde Pública'), ('Tecnólogo em Sistemas Biomédicos', 'Tecnólogo em Sistemas Biomédicos'), ('Terapeuta Cognitivo-Comportamental', 'Terapeuta Cognitivo-Comportamental'), ('Terapeuta Familiar', 'Terapeuta Familiar'), ('Terapeuta Holístico', 'Terapeuta Holístico'), ('Terapeuta Integrativo', 'Terapeuta Integrativo'), ('Terapeuta Ocupacional', 'Terapeuta Ocupacional')], max_length=255),
        ),
        migrations.AlterField(
            model_name='professional',
            name='experience_years',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='professional',
            name='graduation_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='professional',
            name='institution',
            field=models.CharField(max_length=255),
        ),
    ]
