# Generated by Django 5.0.1 on 2026-01-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0005_remove_professional_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professional',
            name='education',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='professional',
            name='neighborhood',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professional',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='professional',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='professional',
            name='street',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='professional',
            name='zip_code',
            field=models.CharField(max_length=9),
        ),
    ]
