# Generated by Django 5.0.1 on 2026-01-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0006_alter_professional_city_alter_professional_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
