# Generated by Django 5.0.1 on 2026-01-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0007_professional_internal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='person_type',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2),
        ),
        migrations.AddField(
            model_name='professional',
            name='technical_manager_cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='technical_manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True),
        ),
    ]
