export const EDUCATION_OPTIONS = [
    'Agente Comunitário de Saúde', 'Agente de Combate às Endemias', 'Acompanhante Terapêutico',
    'Administrador Hospitalar', 'Analista de Regulação em Saúde', 'Antropólogo da Saúde',
    'Aromaterapeuta', 'Arteterapeuta', 'Assistente Social (na saúde)', 'Audiologista',
    'Auxiliar de Enfermagem', 'Auxiliar de Farmácia', 'Auxiliar de Saúde Bucal', 'Bioquímico',
    'Biomédico', 'Biólogo (atuando na saúde)', 'Citotécnico', 'Cosmetólogo', 'Cuidador de Idosos',
    'Dentista (Cirurgião-Dentista)', 'Dosimetrista', 'Doula', 'Educador Físico (Bacharel)',
    'Educador em Saúde', 'Enfermeiro', 'Engenheiro Biomédico', 'Epidemiologista', 'Esteticista',
    'Farmacêutico', 'Farmacêutico Clínico', 'Farmacêutico Hospitalar', 'Farmacêutico Industrial',
    'Fisioterapeuta', 'Fonoaudiólogo', 'Gerontólogo', 'Gestor Hospitalar', 'Gestor em Saúde',
    'Histotécnico', 'Massoterapeuta', 'Musicoterapeuta', 'Naturopata', 'Nutricionista',
    'Obstetriz', 'Optometrista', 'Óptico', 'Operador de Raios-X', 'Ortesista e Protesista',
    'Osteopata', 'Parteira Tradicional', 'Patologista Clínico (não médico)', 'Podólogo',
    'Protético Dentário', 'Psicanalista', 'Psicólogo', 'Quiropraxista', 'Radiologista Tecnólogo',
    'Reflexoterapeuta', 'Sanitarista', 'Sociólogo da Saúde', 'Técnico em Administração Hospitalar',
    'Técnico em Análises Clínicas', 'Técnico em Audiometria', 'Técnico em Banco de Sangue',
    'Técnico em Enfermagem', 'Técnico em Equipamentos Biomédicos', 'Técnico em Farmácia',
    'Técnico em Gerontologia', 'Técnico em Hemoterapia', 'Técnico em Histologia',
    'Técnico em Imobilizações Ortopédicas', 'Técnico em Imagenologia', 'Técnico em Nutrição e Dietética',
    'Técnico em Óptica', 'Técnico em Prótese Dentária', 'Técnico em Radiologia',
    'Técnico em Registros e Informações em Saúde', 'Técnico em Saúde Bucal', 'Técnico em Saúde Pública',
    'Técnico em Vigilância em Saúde', 'Tecnólogo em Análises Clínicas', 'Tecnólogo em Estética e Cosmética',
    'Tecnólogo em Oftálmica', 'Tecnólogo em Radiologia', 'Tecnólogo em Saúde Pública',
    'Tecnólogo em Sistemas Biomédicos', 'Terapeuta Cognitivo-Comportamental', 'Terapeuta Familiar',
    'Terapeuta Holístico', 'Terapeuta Integrativo', 'Terapeuta Ocupacional',
    'Outros'
];
